/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/papers/graph/library": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Library Graph */
        get: operations["library_graph_api_papers_graph_library_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/library/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Library Categories */
        get: operations["list_library_categories_api_papers_library_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/library": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Library */
        get: operations["get_library_api_papers_library_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save Papers */
        post: operations["save_papers_api_papers_save_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{paper_id}/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Paper Ingest Status */
        get: operations["get_paper_ingest_status_api_papers__paper_id__ingest_get"];
        put?: never;
        /**
         * Enqueue Paper Ingest
         * @description Queue canonical PDF parsing/chunking/indexing for one owned paper.
         */
        post: operations["enqueue_paper_ingest_api_papers__paper_id__ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{paper_id}/ingest/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Paper Ingest Job */
        get: operations["get_paper_ingest_job_api_papers__paper_id__ingest__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daily Papers Get */
        get: operations["daily_papers_get_api_papers_daily_get"];
        put?: never;
        /** Daily Papers */
        post: operations["daily_papers_api_papers_daily_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/reading/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log Reading Session */
        post: operations["log_reading_session_api_papers_reading_log_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/reading/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reading Calendar */
        get: operations["reading_calendar_api_papers_reading_calendar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{paper_id}/library-pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Paper Library Pdf */
        get: operations["get_paper_library_pdf_api_papers__paper_id__library_pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{paper_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Paper */
        get: operations["get_paper_api_papers__paper_id__get"];
        /** Update Paper */
        put: operations["update_paper_api_papers__paper_id__put"];
        post?: never;
        /** Delete Paper */
        delete: operations["delete_paper_api_papers__paper_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/daily/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record Daily Recommend Feedback */
        post: operations["record_daily_recommend_feedback_api_papers_daily_feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/paper-reader/opening": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Paper Reader Opening */
        post: operations["paper_reader_opening_api_ai_paper_reader_opening_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/paper-reader/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Paper Reader Chat */
        post: operations["paper_reader_chat_api_ai_paper_reader_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/paper-reader/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Paper Reader History */
        get: operations["paper_reader_history_api_ai_paper_reader_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/search-agent/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search Agent Chat Stream */
        post: operations["search_agent_chat_stream_api_papers_search_agent_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Json */
        get: operations["export_json_api_export_json_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{paper_id}/memory-drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Memory Draft */
        post: operations["create_memory_draft_api_papers__paper_id__memory_drafts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory-drafts/{draft_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Memory Draft */
        get: operations["get_memory_draft_api_memory_drafts__draft_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory-drafts/{draft_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Memory Draft */
        post: operations["cancel_memory_draft_api_memory_drafts__draft_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory-drafts/{draft_id}/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Commit Memory Draft */
        post: operations["commit_memory_draft_api_memory_drafts__draft_id__commit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{paper_id}/memories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Paper Memories */
        get: operations["list_paper_memories_api_papers__paper_id__memories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memories/{memory_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Memory */
        delete: operations["delete_memory_api_memories__memory_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Memory Stats */
        get: operations["memory_stats_api_memory_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List User Memories */
        get: operations["list_user_memories_api_memory_user_get"];
        put?: never;
        /** Create User Memory */
        post: operations["create_user_memory_api_memory_user_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Memory List */
        get: operations["memory_list_api_memory_list_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Verify Token
         * @description Verify the bearer token without exposing it in a query string.
         */
        get: operations["verify_token_api_auth_verify_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Research Sessions */
        get: operations["list_research_sessions_api_research_sessions_get"];
        put?: never;
        /** Create Research Session */
        post: operations["create_research_session_api_research_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Research Session */
        get: operations["get_research_session_api_research_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/sessions/{session_id}/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Research Chat */
        post: operations["research_chat_api_research_sessions__session_id__chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Capabilities
         * @description Expose safe RAG readiness facts without leaking keys or local paths.
         */
        get: operations["health_capabilities_health_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuthResponse */
        AuthResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
            /** User Id */
            user_id?: number | null;
            /** Username */
            username?: string | null;
            /** Token */
            token?: string | null;
        };
        /** Author */
        Author: {
            /** Name */
            name: string;
            /** Affiliation */
            affiliation?: string | null;
            /** Email */
            email?: string | null;
            /** Orcid */
            orcid?: string | null;
            /**
             * Db Id
             * @description 本地 authors 表 id，用于区分同名
             */
            db_id?: number | null;
        };
        /** CommitMemoryDraftRequest */
        CommitMemoryDraftRequest: {
            /** Paper Items */
            paper_items?: components["schemas"]["CommitMemoryItem"][];
            /** Accepted User Items */
            accepted_user_items?: components["schemas"]["CommitMemoryItem"][];
        };
        /** CommitMemoryItem */
        CommitMemoryItem: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "reading_summary" | "key_finding" | "open_question" | "research_decision" | "preference" | "research_goal";
            /** Content */
            content: string;
        };
        /** CreateMemoryDraftRequest */
        CreateMemoryDraftRequest: {
            /** Conversation Id */
            conversation_id: string;
            /** From Turn Id */
            from_turn_id?: number | null;
            /** To Turn Id */
            to_turn_id?: number | null;
        };
        /** CreateResearchSessionRequest */
        CreateResearchSessionRequest: {
            /** Paper Ids */
            paper_ids: number[];
            /** Title */
            title?: string | null;
        };
        /** CreateUserMemoryRequest */
        CreateUserMemoryRequest: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "preference" | "research_goal";
            /** Content */
            content: string;
        };
        /** DailyPaperPickHint */
        DailyPaperPickHint: {
            /**
             * Identity Key
             * @description 身份键，如 arxiv:2401.0001
             */
            identity_key: string;
            /**
             * Pick Kind
             * @description personalized | general
             */
            pick_kind: string;
            /**
             * Explanation
             * @description 入选理由
             * @default
             */
            explanation: string;
        };
        /** DailyPapersRequest */
        DailyPapersRequest: {
            /**
             * Days Back
             * @description arXiv 最近 N 天
             * @default 5
             */
            days_back: number;
            /**
             * Arxiv Max Results
             * @description arXiv 候选数
             * @default 20
             */
            arxiv_max_results: number;
            /**
             * Arxiv Categories
             * @description arXiv 分类过滤
             */
            arxiv_categories?: string[] | null;
            /**
             * Personalized K
             * @description 个性化推荐条数
             * @default 20
             */
            personalized_k: number;
            /**
             * Library Limit
             * @description 库内候选上限
             * @default 800
             */
            library_limit: number;
            /**
             * Force Refresh
             * @description 忽略缓存强制刷新
             * @default false
             */
            force_refresh: boolean;
            /**
             * Use Llm Rank
             * @description 是否启用 LLM 精排
             * @default false
             */
            use_llm_rank: boolean;
            /**
             * Rerank Recall Max
             * @description 精排前召回候选上限
             * @default 24
             */
            rerank_recall_max: number;
            /**
             * Use Llm Theme Keywords
             * @description LLM 生成主题标签
             * @default true
             */
            use_llm_theme_keywords: boolean;
        };
        /** DailyPapersResponse */
        DailyPapersResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
            /** Date Key */
            date_key: string;
            /** Arxiv Latest Total */
            arxiv_latest_total: number;
            /** Arxiv Selected Total */
            arxiv_selected_total: number;
            /** Personalized Total */
            personalized_total: number;
            /** Arxiv Latest */
            arxiv_latest?: components["schemas"]["Paper-Output"][];
            /** Arxiv Selected */
            arxiv_selected?: components["schemas"]["Paper-Output"][];
            /** Personalized */
            personalized?: components["schemas"]["Paper-Output"][];
            /**
             * Memory Keywords Used
             * @description 偏好词摘要
             */
            memory_keywords_used?: string[];
            /**
             * Strategy Explanation
             * @description 推荐策略摘要（≤2 行中文）
             * @default
             */
            strategy_explanation: string;
            /**
             * Personalized Theme Keywords
             * @description 个性化列表主题标签
             */
            personalized_theme_keywords?: string[];
            /**
             * General Theme Keywords
             * @description 精选列表主题标签
             */
            general_theme_keywords?: string[];
            /** Personalized Pick Hints */
            personalized_pick_hints?: components["schemas"]["DailyPaperPickHint"][];
            /** General Pick Hints */
            general_pick_hints?: components["schemas"]["DailyPaperPickHint"][];
        };
        /** DailyRecommendFeedbackRequest */
        DailyRecommendFeedbackRequest: {
            /**
             * Identity Key
             * @description 论文身份标识（如 arxiv:2401.0001 / doi:xxx / title_hash:xxx）
             */
            identity_key: string;
            /**
             * Title
             * @description 论文标题
             */
            title?: string | null;
            /** @description 用户动作 */
            action: components["schemas"]["FeedbackActionEnum"];
            /**
             * Source List
             * @description 推荐来源: personalized 或 general
             */
            source_list?: string | null;
            /**
             * Score At Recommend
             * @description 推荐时的匹配分数
             */
            score_at_recommend?: number | null;
            /**
             * Keywords
             * @description 论文关键词
             */
            keywords?: string[] | null;
            /**
             * Category
             * @description 论文分类
             */
            category?: string | null;
            /**
             * Journal
             * @description 论文期刊/会议（用于负反馈建模）
             */
            journal?: string | null;
            /**
             * Source
             * @description 数据源（用于负反馈建模）
             */
            source?: string | null;
        };
        /** DailyRecommendFeedbackResponse */
        DailyRecommendFeedbackResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
        };
        /** DeletePaperResponse */
        DeletePaperResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
        };
        /**
         * FeedbackActionEnum
         * @enum {string}
         */
        FeedbackActionEnum: "click" | "save" | "skip" | "ignore" | "read";
        /** GraphEdge */
        GraphEdge: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Type */
            type: string;
            /**
             * Weight
             * @default 1
             */
            weight: number;
            /** Evidence */
            evidence?: string | null;
        };
        /** GraphNode */
        GraphNode: {
            /** Id */
            id: string;
            /** Type */
            type: string;
            /** Label */
            label: string;
            /** Paper Id */
            paper_id?: number | null;
            /** Year */
            year?: number | null;
            /** Category */
            category?: string | null;
            /** Journal */
            journal?: string | null;
            /** Venue Type */
            venue_type?: string | null;
            /**
             * Weight
             * @default 1
             */
            weight: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IngestJobReference
         * @description A durable canonical-document ingest job created while saving a paper.
         */
        IngestJobReference: {
            /** Paper Id */
            paper_id: number;
            /** Job Id */
            job_id: string;
            /** Status */
            status: string;
        };
        /** LibraryCategoriesResponse */
        LibraryCategoriesResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
            /**
             * Store Root
             * @default 文献库
             */
            store_root: string;
            /** Folders */
            folders?: components["schemas"]["LibraryCategoryFolder"][];
        };
        /** LibraryCategoryFolder */
        LibraryCategoryFolder: {
            /** Category */
            category: string;
            /** Folder */
            folder: string;
            /** Count */
            count: number;
            /** Children */
            children?: {
                [key: string]: unknown;
            }[];
        };
        /** LibraryGraphResponse */
        LibraryGraphResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
            /** Nodes */
            nodes?: components["schemas"]["GraphNode"][];
            /** Edges */
            edges?: components["schemas"]["GraphEdge"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** Paper */
        "Paper-Input": {
            /** Id */
            id?: number | null;
            /** User Id */
            user_id?: number | null;
            /** Title */
            title: string;
            /** Authors */
            authors?: components["schemas"]["Author"][];
            /** Abstract */
            abstract?: string | null;
            /** Doi */
            doi?: string | null;
            /** Pmid */
            pmid?: string | null;
            /** Arxiv Id */
            arxiv_id?: string | null;
            /** Pmc Id */
            pmc_id?: string | null;
            /** Journal */
            journal?: string | null;
            /**
             * Venue Type
             * @description 会议/期刊类型：conference 或 journal
             */
            venue_type?: string | null;
            /** Year */
            year?: number | null;
            /** Volume */
            volume?: string | null;
            /** Issue */
            issue?: string | null;
            /** Pages */
            pages?: string | null;
            /** Publisher */
            publisher?: string | null;
            /** Pdf Url */
            pdf_url?: string | null;
            /** Source Url */
            source_url?: string | null;
            /**
             * Local Pdf Path
             * @description 本地 PDF 相对路径
             */
            local_pdf_path?: string | null;
            /** Keywords */
            keywords?: string[];
            /** Mesh Terms */
            mesh_terms?: string[];
            /** References */
            references?: string[];
            /**
             * Citations
             * @default 0
             */
            citations: number;
            /** @default unknown */
            source: components["schemas"]["PaperSource"];
            /**
             * Relevance Score
             * @default 0
             */
            relevance_score: number;
            /** Notes */
            notes?: string | null;
            /** Tags */
            tags?: string[];
            /**
             * Category
             * @description 文献库领域（保存时由大模型或手写）
             */
            category?: string | null;
            /** Rating */
            rating?: number | null;
            /** @default unread */
            read_status: components["schemas"]["ReadStatus"];
            /**
             * Importance
             * @default normal
             */
            importance: string;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /** Paper */
        "Paper-Output": {
            /** Id */
            id?: number | null;
            /** Title */
            title: string;
            /** Authors */
            authors?: components["schemas"]["Author"][];
            /** Abstract */
            abstract?: string | null;
            /** Doi */
            doi?: string | null;
            /** Pmid */
            pmid?: string | null;
            /** Arxiv Id */
            arxiv_id?: string | null;
            /** Pmc Id */
            pmc_id?: string | null;
            /** Journal */
            journal?: string | null;
            /**
             * Venue Type
             * @description 会议/期刊类型：conference 或 journal
             */
            venue_type?: string | null;
            /** Year */
            year?: number | null;
            /** Volume */
            volume?: string | null;
            /** Issue */
            issue?: string | null;
            /** Pages */
            pages?: string | null;
            /** Publisher */
            publisher?: string | null;
            /** Pdf Url */
            pdf_url?: string | null;
            /** Source Url */
            source_url?: string | null;
            /**
             * Local Pdf Path
             * @description 本地 PDF 相对路径
             */
            local_pdf_path?: string | null;
            /** Keywords */
            keywords?: string[];
            /** Mesh Terms */
            mesh_terms?: string[];
            /** References */
            references?: string[];
            /**
             * Citations
             * @default 0
             */
            citations: number;
            /** @default unknown */
            source: components["schemas"]["PaperSource"];
            /**
             * Relevance Score
             * @default 0
             */
            relevance_score: number;
            /** Notes */
            notes?: string | null;
            /** Tags */
            tags?: string[];
            /**
             * Category
             * @description 文献库领域（保存时由大模型或手写）
             */
            category?: string | null;
            /** Rating */
            rating?: number | null;
            /** @default unread */
            read_status: components["schemas"]["ReadStatus"];
            /**
             * Importance
             * @default normal
             */
            importance: string;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /** PaperReaderChatRequest */
        PaperReaderChatRequest: {
            /** Paper Id */
            paper_id: number;
            /** Conversation Id */
            conversation_id?: string | null;
            /**
             * Messages
             * @description 兼容旧客户端的字段；服务端不会将其注入模型上下文。阅读历史仅从已持久化且按用户/论文/会话隔离的记录读取。
             */
            messages?: {
                [key: string]: string;
            }[];
            /** User Message */
            user_message: string;
        };
        /** PaperReaderChatResponse */
        PaperReaderChatResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
            /** Reply */
            reply: string;
            /** Conversation Id */
            conversation_id: string;
            /**
             * Pdf Parsing
             * @default false
             */
            pdf_parsing: boolean;
            /**
             * Context Mode
             * @default legacy_fallback
             */
            context_mode: string;
            /** Degradation Flags */
            degradation_flags?: string[];
            /** Related Papers */
            related_papers?: components["schemas"]["Paper-Output"][];
            /** Related Hints */
            related_hints?: {
                [key: string]: unknown;
            }[];
            /** Kg Edges */
            kg_edges?: {
                [key: string]: unknown;
            }[];
            /** Citations */
            citations?: {
                [key: string]: unknown;
            }[];
        };
        /** PaperReaderHistoryItem */
        PaperReaderHistoryItem: {
            /** Id */
            id: number;
            /** Role */
            role: string;
            /** Content */
            content: string;
            /** Created At */
            created_at: number;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /** PaperReaderHistoryResponse */
        PaperReaderHistoryResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
            /** Paper Id */
            paper_id: number;
            /** Conversation Id */
            conversation_id: string;
            /** Turns */
            turns?: components["schemas"]["PaperReaderHistoryItem"][];
        };
        /** PaperReaderOpeningRequest */
        PaperReaderOpeningRequest: {
            /** Paper Id */
            paper_id: number;
            /** Conversation Id */
            conversation_id?: string | null;
        };
        /** PaperReaderOpeningResponse */
        PaperReaderOpeningResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
            /** Opening */
            opening: string;
            /**
             * Pdf Parsing
             * @default false
             */
            pdf_parsing: boolean;
            /** Conversation Id */
            conversation_id: string;
            /**
             * Context Mode
             * @default legacy_fallback
             */
            context_mode: string;
            /** Degradation Flags */
            degradation_flags?: string[];
        };
        /**
         * PaperSource
         * @enum {string}
         */
        PaperSource: "arxiv" | "openalex" | "dblp" | "tavily" | "mcp" | "unknown";
        /** PapersResponse */
        PapersResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
            /** Total */
            total: number;
            /** Papers */
            papers?: components["schemas"]["Paper-Output"][];
        };
        /**
         * ReadStatus
         * @enum {string}
         */
        ReadStatus: "unread" | "reading" | "read";
        /** ReadingCalendarItem */
        ReadingCalendarItem: {
            /**
             * Date
             * @description YYYY-MM-DD
             */
            date: string;
            /**
             * Seconds
             * @default 0
             */
            seconds: number;
            /**
             * Sessions
             * @default 0
             */
            sessions: number;
        };
        /** ReadingCalendarResponse */
        ReadingCalendarResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
            /**
             * Days
             * @default 180
             */
            days: number;
            /** Items */
            items?: components["schemas"]["ReadingCalendarItem"][];
        };
        /** ReadingLogRequest */
        ReadingLogRequest: {
            /** Paper Id */
            paper_id: number;
            /**
             * Duration Sec
             * @description 本次阅读停留时长（秒）
             */
            duration_sec: number;
            /**
             * Client Ts
             * @description 客户端时间戳（秒）；缺省则服务端按当前时间落在当天
             */
            client_ts?: number | null;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** ResearchChatRequest */
        ResearchChatRequest: {
            /** User Message */
            user_message: string;
        };
        /** SavePapersRequest */
        SavePapersRequest: {
            /** Papers */
            papers: components["schemas"]["Paper-Input"][];
            /**
             * Download Pdfs
             * @description 保存后下载 PDF
             * @default false
             */
            download_pdfs: boolean;
            /**
             * Llm Classify
             * @description 大模型划分 category
             * @default true
             */
            llm_classify: boolean;
        };
        /** SavePapersResponse */
        SavePapersResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
            /** Added */
            added: number;
            /**
             * Updated
             * @default 0
             */
            updated: number;
            /** Ids */
            ids?: number[];
            /**
             * Pdf Downloaded
             * @default 0
             */
            pdf_downloaded: number;
            /**
             * Llm Classified
             * @default 0
             */
            llm_classified: number;
            /** Ingest Jobs */
            ingest_jobs?: components["schemas"]["IngestJobReference"][];
            /**
             * Ingest Enqueue Failed
             * @default 0
             */
            ingest_enqueue_failed: number;
        };
        /** SearchAgentMessage */
        SearchAgentMessage: {
            /**
             * Message
             * @description 用户搜索需求
             */
            message: string;
            /**
             * Mode
             * @description accuracy=准确性优先, novelty=新颖性优先
             * @default accuracy
             */
            mode: string;
            /**
             * Use Tavily
             * @description 是否使用 Tavily 预搜索
             * @default false
             */
            use_tavily: boolean;
            /**
             * Deep Search
             * @description 启用深度搜索: 子问题分解+迭代检索+RRF融合
             * @default false
             */
            deep_search: boolean;
            /**
             * History
             * @description 对话历史
             */
            history?: {
                [key: string]: string;
            }[];
        };
        /** UpdatePaperRequest */
        UpdatePaperRequest: {
            /** Notes */
            notes?: string | null;
            /** Tags */
            tags?: string[] | null;
            /** Category */
            category?: string | null;
            /** Rating */
            rating?: number | null;
            read_status?: components["schemas"]["ReadStatus"] | null;
            /** Importance */
            importance?: string | null;
        };
        /** UpdatePaperResponse */
        UpdatePaperResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
            /** Updated Fields */
            updated_fields?: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    library_graph_api_papers_graph_library_get: {
        parameters: {
            query?: {
                limit?: number;
                category?: string | null;
                include_authors?: boolean;
                include_keywords?: boolean;
                relation_edge_limit?: number;
                focus_paper_id?: number | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryGraphResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_library_categories_api_papers_library_categories_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryCategoriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_library_api_papers_library_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                q?: string | null;
                year_from?: number | null;
                year_to?: number | null;
                read_status?: components["schemas"]["ReadStatus"] | null;
                /** @description 逗号分隔标签 */
                tags?: string | null;
                /** @description 领域筛选 */
                category?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PapersResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_papers_api_papers_save_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavePapersRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavePapersResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_paper_ingest_status_api_papers__paper_id__ingest_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                paper_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enqueue_paper_ingest_api_papers__paper_id__ingest_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                paper_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_paper_ingest_job_api_papers__paper_id__ingest__job_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                paper_id: number;
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    daily_papers_get_api_papers_daily_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    daily_papers_api_papers_daily_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DailyPapersRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyPapersResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    log_reading_session_api_papers_reading_log_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReadingLogRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reading_calendar_api_papers_reading_calendar_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingCalendarResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_paper_library_pdf_api_papers__paper_id__library_pdf_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                paper_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_paper_api_papers__paper_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                paper_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Paper-Output"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_paper_api_papers__paper_id__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                paper_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePaperRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdatePaperResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_paper_api_papers__paper_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                paper_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletePaperResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_daily_recommend_feedback_api_papers_daily_feedback_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DailyRecommendFeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyRecommendFeedbackResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    paper_reader_opening_api_ai_paper_reader_opening_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaperReaderOpeningRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperReaderOpeningResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    paper_reader_chat_api_ai_paper_reader_chat_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaperReaderChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperReaderChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    paper_reader_history_api_ai_paper_reader_history_get: {
        parameters: {
            query: {
                paper_id: number;
                limit?: number;
                conversation_id?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperReaderHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_agent_chat_stream_api_papers_search_agent_stream_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchAgentMessage"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_json_api_export_json_get: {
        parameters: {
            query?: {
                scope?: string;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_memory_draft_api_papers__paper_id__memory_drafts_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                paper_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMemoryDraftRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_memory_draft_api_memory_drafts__draft_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_memory_draft_api_memory_drafts__draft_id__cancel_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    commit_memory_draft_api_memory_drafts__draft_id__commit_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                authorization?: string | null;
            };
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommitMemoryDraftRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_paper_memories_api_papers__paper_id__memories_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                paper_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_memory_api_memories__memory_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                memory_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    memory_stats_api_memory_stats_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_user_memories_api_memory_user_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_user_memory_api_memory_user_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserMemoryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    memory_list_api_memory_list_get: {
        parameters: {
            query?: {
                scope_type?: string | null;
                scope_id?: string | null;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_token_api_auth_verify_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_research_sessions_api_research_sessions_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_research_session_api_research_sessions_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateResearchSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_research_session_api_research_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    research_chat_api_research_sessions__session_id__chat_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResearchChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_capabilities_health_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
